services:
  caddy:
      image: caddy:2.4.3-alpine
      restart: unless-stopped
      command: caddy reverse-proxy --from ${SITE_ADDRESS} --to http://web:3000
      ports:
        - 80:80
        - 443:443
      volumes:
        - caddy:/data
      depends_on:
        - web
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  bundle:
  caddy:
